apiVersion: v1
kind: Service
metadata:
  name: login-signup-docker
spec:
  selector:
    app: login-signup-docker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
